[package]
name = "castellan"
version = "0.1.0-dev"
authors = ["Arad Fadaei <arad@fadaei.dev>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.1", features = ["router", "fullstack"] }
tokio = { version = "1.50.0", features = ["full"], optional = true }


[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
server = ["dioxus/server", "dep:tokio"]
# web = ["dioxus/web"]
# mobile = ["dioxus/mobile"]
