[app_log]
level = "DEBUG"
timestamp_mode = "utc"

[scroll]
line_step = 1
page_step = 25

[keybinds.exit_app]
code = "c"
ctrl = true
alt = false
shift = false

[keybinds.enter_input_mode]
code = "i"
ctrl = false
alt = false
shift = false

[keybinds.exit_input_mode]
code = "esc"
ctrl = false
alt = false
shift = false

[keybinds.new_chat_tab]
code = "t"
ctrl = true
alt = false
shift = false

[keybinds.next_tab]
code = "tab"
ctrl = false
alt = false
shift = false

[keybinds.prev_tab]
code = "backtab"
ctrl = false
alt = false
shift = false

[keybinds.backspace]
code = "backspace"
ctrl = false
alt = false
shift = false

[keybinds.submit]
code = "enter"
ctrl = false
alt = false
shift = false

[keybinds.scroll_up]
code = "k"
ctrl = false
alt = false
shift = false

[keybinds.scroll_down]
code = "j"
ctrl = false
alt = false
shift = false

[keybinds.page_up]
code = "k"
ctrl = false
alt = false
shift = true

[keybinds.page_down]
code = "j"
ctrl = false
alt = false
shift = true

[keybinds.scroll_to_bottom]
code = "end"
ctrl = false
alt = false
shift = false

[keybinds.close_current_tab]
code = "w"
ctrl = true
alt = false
shift = false

[keybinds.rename_current_tab]
code = "r"
ctrl = true
alt = false
shift = false